name: flutter_app
description: "A new Flutter project with IDMC Integration."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  file_picker: ^5.3.1  # Use latest compatible version
  flutter:
    sdk: flutter
  http: ^0.13.5
  image_picker: ^0.8.7
  video_player: ^2.6.1
  path_provider: ^2.0.15
  location: ^4.4.0
  charts_flutter: ^0.12.0
  intl: ^0.17.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
